import Head from "next/head";
import { About, Contact, Introduction, Work } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Introduction />
      <Work />
      <About />
      <Contact />
    </div>
  );
}
